/* 지역 데이터 — 시도 17개 · 시군구 234곳. 전 지역에 전용 페이지가 있다.
   새 지역을 추가하면 _content/지역페이지생성.ps1 을 다시 돌리고 이 파일도 다시 만든다. */
window.PICK_REGIONS=[
  {p:'서울',full:'서울 · 25곳',items:['강남구','강동구','강북구','강서구','관악구','광진구','구로구','금천구','노원구','도봉구','동대문구','동작구','마포구','서대문구','서초구','성동구','성북구','송파구','양천구','영등포구','용산구','은평구','종로구','중구','중랑구']},
  {p:'인천',full:'인천 · 13곳',items:['인천 중구','인천 동구','인천 미추홀구','인천 연수구','인천 남동구','인천 부평구','인천 계양구','인천 검단구','인천 영종구','인천 제물포구','인천 서해구','인천 강화군','인천 옹진군']},
  {p:'경기',full:'경기 · 31곳',items:['이천','안성','양주','포천','여주','동두천','과천','의왕','가평','연천','양평','수원','성남','고양','용인','부천','안산','안양','화성','남양주','평택','의정부','시흥','파주','김포','광명','광주','군포','하남','오산','구리']},
  {p:'강원',full:'강원 · 18곳',items:['춘천','원주','강릉','동해','태백','속초','삼척','홍천','횡성','영월','평창','정선','철원','화천','양구','인제','강원 고성','양양']},
  {p:'충북',full:'충북 · 14곳',items:['충주','제천','보은','옥천','영동','증평','진천','괴산','음성','단양','청주 상당구','청주 서원구','청주 흥덕구','청주 청원구']},
  {p:'충남',full:'충남 · 15곳',items:['천안','공주','보령','아산','서산','논산','계룡','당진','금산','부여','서천','청양','홍성','예산','태안']},
  {p:'대전',full:'대전 · 5곳',items:['대전 동구','대전 중구','대전 서구','대전 유성구','대전 대덕구']},
  {p:'세종',full:'세종 · 1곳',items:['세종']},
  {p:'전북',full:'전북 · 14곳',items:['익산','정읍','남원','김제','완주','진안','무주','장수','임실','순창','고창','부안','전주','군산']},
  {p:'전남',full:'전남 · 22곳',items:['목포','여수','순천','나주','광양','담양군','곡성군','구례군','고흥군','보성군','화순군','장흥군','강진군','해남군','영암군','무안군','함평군','영광군','장성군','완도군','진도군','신안군']},
  {p:'광주',full:'광주 · 5곳',items:['광주 동구','광주 서구','광주 남구','광주 북구','광산구']},
  {p:'경북',full:'경북 · 22곳',items:['문경','의성','청송','영양','영덕','청도','고령','성주','예천','봉화','울진','울릉','포항','경주','구미','안동','경산','김천','영주','상주','영천','칠곡군']},
  {p:'경남',full:'경남 · 18곳',items:['의령','창녕','경남 고성','남해','하동','산청','함양','합천','창원','김해','진주','양산','거제','통영','사천','밀양','함안군','거창군']},
  {p:'대구',full:'대구 · 8곳',items:['대구 중구','대구 동구','대구 서구','대구 남구','대구 북구','수성구','달서구','달성군']},
  {p:'부산',full:'부산 · 16곳',items:['부산 중구','부산 서구','부산 동구','부산 영도구','부산진구','동래구','부산 남구','부산 북구','해운대구','사하구','금정구','부산 강서구','연제구','수영구','사상구','기장군']},
  {p:'울산',full:'울산 · 5곳',items:['울산 중구','울산 남구','울산 동구','울산 북구','울주군']},
  {p:'제주',full:'제주 · 2곳',items:['제주','서귀포']}
];
window.PICK_REGION_PAGES={
  '충주':'region/chungbuk-chungju.html',
  '제천':'region/chungbuk-jecheon.html',
  '보은':'region/chungbuk-boeun.html',
  '옥천':'region/chungbuk-okcheon.html',
  '영동':'region/chungbuk-yeongdong.html',
  '증평':'region/chungbuk-jeungpyeong.html',
  '진천':'region/chungbuk-jincheon.html',
  '괴산':'region/chungbuk-goesan.html',
  '음성':'region/chungbuk-eumseong.html',
  '단양':'region/chungbuk-danyang.html',
  '익산':'region/jeonbuk-iksan.html',
  '정읍':'region/jeonbuk-jeongeup.html',
  '남원':'region/jeonbuk-namwon.html',
  '김제':'region/jeonbuk-gimje.html',
  '완주':'region/jeonbuk-wanju.html',
  '진안':'region/jeonbuk-jinan.html',
  '무주':'region/jeonbuk-muju.html',
  '장수':'region/jeonbuk-jangsu.html',
  '임실':'region/jeonbuk-imsil.html',
  '순창':'region/jeonbuk-sunchang.html',
  '고창':'region/jeonbuk-gochang.html',
  '부안':'region/jeonbuk-buan.html',
  '이천':'region/gyeonggi-icheon.html',
  '안성':'region/gyeonggi-anseong.html',
  '양주':'region/gyeonggi-yangju.html',
  '포천':'region/gyeonggi-pocheon.html',
  '여주':'region/gyeonggi-yeoju.html',
  '동두천':'region/gyeonggi-dongducheon.html',
  '과천':'region/gyeonggi-gwacheon.html',
  '의왕':'region/gyeonggi-uiwang.html',
  '가평':'region/gyeonggi-gapyeong.html',
  '연천':'region/gyeonggi-yeoncheon.html',
  '양평':'region/gyeonggi-yangpyeong.html',
  '문경':'region/gyeongbuk-mungyeong.html',
  '의성':'region/gyeongbuk-uiseong.html',
  '청송':'region/gyeongbuk-cheongsong.html',
  '영양':'region/gyeongbuk-yeongyang.html',
  '영덕':'region/gyeongbuk-yeongdeok.html',
  '청도':'region/gyeongbuk-cheongdo.html',
  '고령':'region/gyeongbuk-goryeong.html',
  '성주':'region/gyeongbuk-seongju.html',
  '예천':'region/gyeongbuk-yecheon.html',
  '봉화':'region/gyeongbuk-bonghwa.html',
  '울진':'region/gyeongbuk-uljin.html',
  '울릉':'region/gyeongbuk-ulleung.html',
  '의령':'region/gyeongnam-uiryeong.html',
  '창녕':'region/gyeongnam-changnyeong.html',
  '경남 고성':'region/gyeongnam-goseong.html',
  '남해':'region/gyeongnam-namhae.html',
  '하동':'region/gyeongnam-hadong.html',
  '산청':'region/gyeongnam-sancheong.html',
  '함양':'region/gyeongnam-hamyang.html',
  '합천':'region/gyeongnam-hapcheon.html',
  '춘천':'region/gangwon-chuncheon.html',
  '원주':'region/gangwon-wonju.html',
  '강릉':'region/gangwon-gangneung.html',
  '동해':'region/gangwon-donghae.html',
  '태백':'region/gangwon-taebaek.html',
  '속초':'region/gangwon-sokcho.html',
  '삼척':'region/gangwon-samcheok.html',
  '홍천':'region/gangwon-hongcheon.html',
  '횡성':'region/gangwon-hoengseong.html',
  '영월':'region/gangwon-yeongwol.html',
  '평창':'region/gangwon-pyeongchang.html',
  '정선':'region/gangwon-jeongseon.html',
  '철원':'region/gangwon-cheorwon.html',
  '화천':'region/gangwon-hwacheon.html',
  '양구':'region/gangwon-yanggu.html',
  '인제':'region/gangwon-inje.html',
  '강원 고성':'region/gangwon-goseong.html',
  '양양':'region/gangwon-yangyang.html',
  '천안':'region/chungnam-cheonan.html',
  '공주':'region/chungnam-gongju.html',
  '보령':'region/chungnam-boryeong.html',
  '아산':'region/chungnam-asan.html',
  '서산':'region/chungnam-seosan.html',
  '논산':'region/chungnam-nonsan.html',
  '계룡':'region/chungnam-gyeryong.html',
  '당진':'region/chungnam-dangjin.html',
  '금산':'region/chungnam-geumsan.html',
  '부여':'region/chungnam-buyeo.html',
  '서천':'region/chungnam-seocheon.html',
  '청양':'region/chungnam-cheongyang.html',
  '홍성':'region/chungnam-hongseong.html',
  '예산':'region/chungnam-yesan.html',
  '태안':'region/chungnam-taean.html',
  '부산 중구':'region/busan-junggu.html',
  '부산 서구':'region/busan-seogu.html',
  '부산 동구':'region/busan-donggu.html',
  '부산 영도구':'region/busan-yeongdo.html',
  '부산진구':'region/busan-busanjin.html',
  '동래구':'region/busan-dongnae.html',
  '부산 남구':'region/busan-namgu.html',
  '부산 북구':'region/busan-bukgu.html',
  '해운대구':'region/busan-haeundae.html',
  '사하구':'region/busan-saha.html',
  '금정구':'region/busan-geumjeong.html',
  '부산 강서구':'region/busan-gangseo.html',
  '연제구':'region/busan-yeonje.html',
  '수영구':'region/busan-suyeong.html',
  '사상구':'region/busan-sasang.html',
  '기장군':'region/busan-gijang.html',
  '대구 중구':'region/daegu-junggu.html',
  '대구 동구':'region/daegu-donggu.html',
  '대구 서구':'region/daegu-seogu.html',
  '대구 남구':'region/daegu-namgu.html',
  '대구 북구':'region/daegu-bukgu.html',
  '수성구':'region/daegu-suseong.html',
  '달서구':'region/daegu-dalseo.html',
  '달성군':'region/daegu-dalseong.html',
  '울산 중구':'region/ulsan-junggu.html',
  '울산 남구':'region/ulsan-namgu.html',
  '울산 동구':'region/ulsan-donggu.html',
  '울산 북구':'region/ulsan-bukgu.html',
  '울주군':'region/ulsan-ulju.html',
  '광주 동구':'region/gwangju-donggu.html',
  '광주 서구':'region/gwangju-seogu.html',
  '광주 남구':'region/gwangju-namgu.html',
  '광주 북구':'region/gwangju-bukgu.html',
  '광산구':'region/gwangju-gwangsan.html',
  '목포':'region/jeonnam-mokpo.html',
  '여수':'region/jeonnam-yeosu.html',
  '순천':'region/jeonnam-suncheon.html',
  '나주':'region/jeonnam-naju.html',
  '광양':'region/jeonnam-gwangyang.html',
  '담양군':'region/jeonnam-damyang.html',
  '곡성군':'region/jeonnam-gokseong.html',
  '구례군':'region/jeonnam-gurye.html',
  '고흥군':'region/jeonnam-goheung.html',
  '보성군':'region/jeonnam-boseong.html',
  '화순군':'region/jeonnam-hwasun.html',
  '장흥군':'region/jeonnam-jangheung.html',
  '강진군':'region/jeonnam-gangjin.html',
  '해남군':'region/jeonnam-haenam.html',
  '영암군':'region/jeonnam-yeongam.html',
  '무안군':'region/jeonnam-muan.html',
  '함평군':'region/jeonnam-hampyeong.html',
  '영광군':'region/jeonnam-yeonggwang.html',
  '장성군':'region/jeonnam-jangseong.html',
  '완도군':'region/jeonnam-wando.html',
  '진도군':'region/jeonnam-jindo.html',
  '신안군':'region/jeonnam-sinan.html',
  '전주':'region/jeonbuk-jeonju.html',
  '군산':'region/jeonbuk-gunsan.html',
  '강남구':'region/seoul-gangnam.html',
  '강동구':'region/seoul-gangdong.html',
  '강북구':'region/seoul-gangbuk.html',
  '강서구':'region/seoul-gangseo.html',
  '관악구':'region/seoul-gwanak.html',
  '광진구':'region/seoul-gwangjin.html',
  '구로구':'region/seoul-guro.html',
  '금천구':'region/seoul-geumcheon.html',
  '노원구':'region/seoul-nowon.html',
  '도봉구':'region/seoul-dobong.html',
  '동대문구':'region/seoul-dongdaemun.html',
  '동작구':'region/seoul-dongjak.html',
  '마포구':'region/seoul-mapo.html',
  '서대문구':'region/seoul-seodaemun.html',
  '서초구':'region/seoul-seocho.html',
  '성동구':'region/seoul-seongdong.html',
  '성북구':'region/seoul-seongbuk.html',
  '송파구':'region/seoul-songpa.html',
  '양천구':'region/seoul-yangcheon.html',
  '영등포구':'region/seoul-yeongdeungpo.html',
  '용산구':'region/seoul-yongsan.html',
  '은평구':'region/seoul-eunpyeong.html',
  '종로구':'region/seoul-jongno.html',
  '중구':'region/seoul-junggu.html',
  '중랑구':'region/seoul-jungnang.html',
  '인천 중구':'region/incheon-junggu.html',
  '인천 동구':'region/incheon-donggu.html',
  '인천 미추홀구':'region/incheon-michuhol.html',
  '인천 연수구':'region/incheon-yeonsu.html',
  '인천 남동구':'region/incheon-namdong.html',
  '인천 부평구':'region/incheon-bupyeong.html',
  '인천 계양구':'region/incheon-gyeyang.html',
  '인천 검단구':'region/incheon-geomdan.html',
  '인천 영종구':'region/incheon-yeongjong.html',
  '인천 제물포구':'region/incheon-jemulpo.html',
  '인천 서해구':'region/incheon-seogu.html',
  '인천 강화군':'region/incheon-ganghwa.html',
  '인천 옹진군':'region/incheon-ongjin.html',
  '수원':'region/gyeonggi-suwon.html',
  '성남':'region/gyeonggi-seongnam.html',
  '고양':'region/gyeonggi-goyang.html',
  '용인':'region/gyeonggi-yongin.html',
  '부천':'region/gyeonggi-bucheon.html',
  '안산':'region/gyeonggi-ansan.html',
  '안양':'region/gyeonggi-anyang.html',
  '화성':'region/gyeonggi-hwaseong.html',
  '남양주':'region/gyeonggi-namyangju.html',
  '평택':'region/gyeonggi-pyeongtaek.html',
  '의정부':'region/gyeonggi-uijeongbu.html',
  '시흥':'region/gyeonggi-siheung.html',
  '파주':'region/gyeonggi-paju.html',
  '김포':'region/gyeonggi-gimpo.html',
  '광명':'region/gyeonggi-gwangmyeong.html',
  '광주':'region/gyeonggi-gwangju.html',
  '군포':'region/gyeonggi-gunpo.html',
  '하남':'region/gyeonggi-hanam.html',
  '오산':'region/gyeonggi-osan.html',
  '구리':'region/gyeonggi-guri.html',
  '대전 동구':'region/daejeon-donggu.html',
  '대전 중구':'region/daejeon-junggu.html',
  '대전 서구':'region/daejeon-seogu.html',
  '대전 유성구':'region/daejeon-yuseong.html',
  '대전 대덕구':'region/daejeon-daedeok.html',
  '세종':'region/sejong.html',
  '청주 상당구':'region/cheongju-sangdang.html',
  '청주 서원구':'region/cheongju-seowon.html',
  '청주 흥덕구':'region/cheongju-heungdeok.html',
  '청주 청원구':'region/cheongju-cheongwon.html',
  '제주':'region/jeju-jeju.html',
  '서귀포':'region/jeju-seogwipo.html',
  '포항':'region/gyeongbuk-pohang.html',
  '경주':'region/gyeongbuk-gyeongju.html',
  '구미':'region/gyeongbuk-gumi.html',
  '안동':'region/gyeongbuk-andong.html',
  '경산':'region/gyeongbuk-gyeongsan.html',
  '김천':'region/gyeongbuk-gimcheon.html',
  '영주':'region/gyeongbuk-yeongju.html',
  '상주':'region/gyeongbuk-sangju.html',
  '영천':'region/gyeongbuk-yeongcheon.html',
  '칠곡군':'region/gyeongbuk-chilgok.html',
  '창원':'region/gyeongnam-changwon.html',
  '김해':'region/gyeongnam-gimhae.html',
  '진주':'region/gyeongnam-jinju.html',
  '양산':'region/gyeongnam-yangsan.html',
  '거제':'region/gyeongnam-geoje.html',
  '통영':'region/gyeongnam-tongyeong.html',
  '사천':'region/gyeongnam-sacheon.html',
  '밀양':'region/gyeongnam-miryang.html',
  '함안군':'region/gyeongnam-haman.html',
  '거창군':'region/gyeongnam-geochang.html'
};
